services:
  - type: web
    name: scalex-api
    env: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: HF_TOKEN
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: DB_PATH
        value: /data/scalex.db
    disk:
      name: scalex-db
      mountPath: /data
      sizeGB: 1
